### ISSUE TITLE
Creates only one issue for multiple identical fixme's on separate files

### ISSUE THREAD

**Issue by codingmanu** [ribtoks/tdg#5]
Again, thanks a lot for this action! We're using it on our project and it's helping a lot for cleaning the codebase.

One thing I just noticed is that if I add the same identical comment in two separate files, for example something like below, it will only add one issue.

```
// FIXME: Temporary decoding
// Real value should be integers. Currently having both options until backend fixes it.
```

The title and the value are correct and they get filled in the correct places, so no issues there, but at the end, I only get one GH issue added. I believe since they're in separate files, they should be two different issues.

Thanks!

**Comment by ribtoks** [comment]
@codingmanu moved this issue to `tdg` repository since it's where it belongs

**Comment by codingmanu** [comment]
Thanks for the update! I think I might have another request for this... If we have the same exact issue twice in the same file, it only creates it once. Should we add the line number of the keyword (TODO, FIXME, etc) to the md5? Sorry I didn't notice before.

**Comment by ribtoks** [comment]
I think this is reasonable to skip exact duplicate comments in the same file on different lines.
